h2:
    console:
        enabled: false
micronaut:
    server:
        port: 8080
    application:
        name: micronaut-hibernate-jpa

datasources:
  default:
    url: jdbc:h2:mem:todoDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
